routes/routes.py
from flask import Blueprint, render_template, session, redirect, url_for, request, flash,jsonify, send_file, request, Response
from service.gasto_service import GastoService
from io import BytesIO
import pandas as pd
from xhtml2pdf import pisa
import random
from datetime import datetime
from datetime import date
from collections import defaultdict
import calendar

from service.despesa_service import DespesaService

from service.admin_service import AdminService

gasto_bp = Blueprint('gasto', __name__)
despesa_bp = Blueprint('despesa', __name__)
admin_bp = Blueprint('admin', __name__)

mensagens_erro = [
    "Senha ou usuario errado 🖕🏼 ",
    "Verifique suas credenciais ⚠️",
    "Seu usuario pode estar inativo 😕",
    "Cara, olha o que tu ta digitando 🤦🏽‍♂️",
    "Acesso negado! você é gay 🏳️‍🌈",
    "Tu é burro(a) ou tu é burro(a)? 🤦🏽‍♂️",
    "Vai bloquear teu usuario 😅",
    "Mds, quem sabe clica em redefinir senha 🤦🏽‍♂️",
]

#####ROTAS#####

def init_routes(app, gasto_service,despesa_service,admin_service):
    print(app.url_map)
    app.register_blueprint(gasto_bp)
    app.register_blueprint(despesa_bp)
    app.register_blueprint(admin_bp)

    # Armazena a instância do service dentro do blueprint
    gasto_bp.gasto_service = gasto_service
    despesa_bp.despesa_service = despesa_service
    admin_bp.admin_service = admin_service
    
#def configure_routes(app, gasto_service):
@gasto_bp.route('/')
def login():
    return render_template('login.html')

@gasto_bp.route('/voltar_ao_login', methods=['GET','POST'])
def voltar_ao_login():
    return render_template('voltar_ao_login.html')

@gasto_bp.route('/login', methods=['POST'])
def login_post():
    print('abner')
    if request.method == 'POST':
        usuario = request.form['email']
        print(usuario)
        senha = request.form['senha']
        print(senha)

        usuario_bd =  gasto_bp.gasto_service.validar_login(usuario, senha)

        if usuario_bd is not None:
            
            session['usuario'] = usuario_bd
            
            dados = gasto_bp.gasto_service.filtrarGastos('mesatual',usuario_bd,'N')

            total_gasto = sum([
                float(item.get('valor', 0)) 
                for item in dados 
                if isinstance(item.get('valor', 0), (int, float)) or str(item.get('valor', 0)).replace('.', '', 1).isdigit()
            ])

            return redirect(url_for('gasto.index'))  # Redireciona para a tela principal
        else:
            erro = random.choice(mensagens_erro)
            flash(erro,"danger")
    return render_template('login.html')


@gasto_bp.route('/index')
def index():
   
    if 'usuario' not in session:

        return redirect(url_for('gasto.login'))

    usuario = session['usuario']  # Só acessa se já tiver passado pela verificação

    #verifica se é administrador
    if usuario == 'admin' or usuario == 'adminstrador':
        return redirect(url_for('admin.admin'))

    dados = gasto_bp.gasto_service.filtrarGastos('mesatual',usuario,'N') #verifica_dados_bd(usuario)

    if not dados:
        dados = [('Alimentação', 0), ('Saúde', 0), ('Mobilidade', 0), ('Entretenimento', 0), ('Moradia', 0), ('Outros', 0), ('Dívidas', 0), ('Educação', 0)]

    total_gasto = sum([
    float(item['valor']) if isinstance(item, dict) and 'valor' in item else float(item[0])
    for item in dados
    if (
        (isinstance(item, dict) and isinstance(item.get('valor', 0), (int, float))) or 
        (isinstance(item, tuple) and len(item) > 0 and str(item[0]).replace('.', '', 1).isdigit())
    )
    ])

    #verifica se é conta casal e exibe dropdon
    tem_conjuge = gasto_bp.gasto_service.tem_conjuge(usuario)

    return render_template('index.html',usuario=usuario,temConjuge=tem_conjuge)

@gasto_bp.route('/cadastrar_gasto', methods=['GET', 'POST'])
def cadastrar_gasto():
    if request.method == 'POST':
        print('cad entrou')
        if 'usuario' not in session:
            flash('Você precisa estar logado para adicionar um gasto.')
            return redirect(url_for('gasto.login')) 

        gasto = request.form['gasto']
        valor = request.form['valor']
        data = request.form['data']
        categoria = request.form['categoria']
        
        usuario = session['usuario']
        
        # Salvar o gasto no banco
        sucesso = gasto_bp.gasto_service.salvar_gasto(gasto, valor, data, categoria,usuario)
        #flash('Gasto cadastrado com sucesso!', 'success')  

        return """<script>                    
                    window.location.href = '/extrato';
                </script>"""

    # return render_template('cadastrar_gasto.html')
    return extrato()  

@gasto_bp.route('/extrato', methods=['GET', 'POST'])
@gasto_bp.route('/extrato/<isCasal>', methods=['GET', 'POST'])
def extrato():
    usuario = session['usuario']

    if request.is_json:
        data = request.get_json()
        isCasal = data.get('isCasal')
    else:
        isCasal = request.form.get('isCasal')

    if request.method == 'GET':
        isCasal =request.args.get('isCasal')

    #page = request.args.get('page', 1, type=int)  # Obtém o número da página (padrão é 1)
    #per_page = 12  # Número de gastos por página
    
     # pega data atual
    hoje = date.today()
    primeiro_dia = hoje.replace(day=1)

    # Pega filtros da URL ou define padrão
    data_inicio = request.args.get('data_inicio') or primeiro_dia.strftime('%Y-%m-%d')
    data_fim = request.args.get('data_fim') or hoje.strftime('%Y-%m-%d')
    categoria = request.args.get('categoria') or 'Todas'

    # Busca os gastos ordenados do mais recente para o mais antigo
    gastos = gasto_bp.gasto_service.extrato_gastos(usuario,data_inicio,data_fim,categoria,isCasal)  

    total_gastos = len(gastos)

    #start = (page - 1) * per_page
    #end = start + per_page

    #gastos_pagina = gastos[start:end]

    # Agrupar os gastos por data
    gastos_agrupados = defaultdict(list)
    for gasto in gastos:
       data = gasto[3]  # Supondo que o 4º item (índice 3) seja a data
       gastos_agrupados[data].append(gasto)


    # lista de categorias
    categorias = gasto_bp.gasto_service.get_categorias_disponiveis(usuario)

    #gastos_pagina = gastos[start:end]

    soma_gastos = 0

    #se for geral do filtro selecionado
    soma_gastos = sum(gasto[2] for gasto in gastos)

    #verifica se é conta casal e exibe dropdon
    tem_conjuge = gasto_bp.gasto_service.tem_conjuge(usuario)

    if isCasal is None:
        isCasal ='N'

    return render_template(
        'extrato.html',
        gastos_agrupados=gastos_agrupados,
        #page=page,
        total=total_gastos,
        #per_page=per_page,
        now=datetime.now(),
        data_inicio=data_inicio,
        data_fim=data_fim,
        categoria=categoria,
        soma_gastos=soma_gastos
        ,usuario =usuario,
        isCasal=isCasal,
        temConjuge=tem_conjuge
    )


@gasto_bp.route('/filtrarGastos/<periodo>/<isCasal>')
def filtrar(periodo,isCasal):
    usuario = session['usuario']

    dados = gasto_bp.gasto_service.filtrarGastos(periodo,usuario,isCasal)
    return jsonify(dados)

@gasto_bp.route('/filtrarGastosMensais/<isCasal>')
def filtrarMesAno(isCasal):
    usuario = session['usuario']

    if isCasal is None:
    
        if request.is_json:
            data = request.get_json()
            isCasal = data.get('isCasal')
        else:
            isCasal = request.form.get('isCasal')

        if request.method == 'GET':
            isCasal =request.args.get('isCasal')

    dados = gasto_bp.gasto_service.filtrarGastosMensais(usuario,isCasal)
    return jsonify(dados)


@gasto_bp.route("/cadastro", methods=["GET", "POST"])
def cadastro():
    if request.method == "POST":
        usuario = request.form["email"]
        senha = request.form["senha"]
        nome = request.form["nome"]
        telefone = request.form["telefone"]

        dados = gasto_bp.gasto_service.valida_usuario_existente(usuario,senha,nome,telefone)   
        
        if dados:
            flash("Usuário já existe! 🤦🏽‍♂️")
            return redirect(url_for('gasto.cadastro',usuario=usuario)) 

        flash("Usuário cadastrado com sucesso! 😄", "success")

        return render_template("cadastro.html",usuario=usuario)
    
    return render_template("cadastro.html")


@gasto_bp.route('/esqueci', methods=['GET', 'POST'])
def esqueci():
    return render_template("esqueci.html")    

@gasto_bp.route('/editar_gasto', methods=[ 'POST'])
def editar_gasto():

    if 'usuario' not in session:
        flash('Você precisa estar logado para adicionar um gasto.')
        return redirect(url_for('gasto.login')) 

    gasto = request.form['gasto']
    valor = request.form['valor']
    data = request.form['data']
    categoria = request.form['categoria']
    
    id = request.form['id']

    # usuario = session['usuario']
    
    gasto_bp.gasto_service.editar_gasto(gasto,categoria,valor,data,id)

    return extrato() 

@gasto_bp.route('/deletar_gasto', methods=['POST'])
def deletar_gasto():

    if 'usuario' not in session:
        flash('Você precisa estar logado para deletar um gasto.')
        return redirect(url_for('gasto.login')) 

    id_gasto = request.form.get('id')

    print('gasto' + id_gasto)

    if not id_gasto:
        # flash('ID do gasto não fornecido!', 'danger')
        return redirect(url_for('gasto.extrato')) 

    try:
        gasto_bp.gasto_service.deletar_gasto(id_gasto)
        # flash('Gasto deletado com sucesso!', 'success')
    except Exception as e:
        print("Erro ao deletar gasto:", e)
        flash('Erro ao tentar deletar o gasto. 😓', 'danger')

    return extrato() 


@despesa_bp.route('/despesas', methods=['GET','POST'])
@despesa_bp.route('/despesas/<isCasal>', methods=['GET','POST'])
def despesas(): 
    usuario = session['usuario']
    
    if request.is_json:
        data = request.get_json()
        isCasal = data.get('isCasal')
    else:
        isCasal = request.form.get('isCasal')

templates/configuracoes.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/configuracoes.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/comum.css') }}">
  <title>Configurações</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  
  <script src="static/js/comum.js" defer></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/config.css') }}">
</head>
<body>

  <div class="header-bar center">
    <div class="logo-text">
      <img src="{{ url_for('static', filename='images/A&A.png') }}" alt="Logo" class="logo">
      <span class="company-name">A&A - Finance Dashboard</span>
    </div>

    <div class="user-info">
      <div class="dropdown">
        <div class="dropdown-toggle" onclick="toggleDropdown()">
          <span class="material-icons user-icon">person</span>
        </div>
    
        <div id="main-dropdown" class="dropdown-menu">
          <div class="profile-header">
            <span  id="user-icon" class="material-icons profile-icon">person</span>
            <div  id="current-username"  class="profile-name">{{ usuario.split('@')[0] | upper }}</div>
          </div>
    
          <div class="dropdown-item" onclick="toggleModeDropdown()">
            Modo
            <span class="material-icons">expand_more</span>
          </div>
    
          <!-- submenu do modo -->
          <div id="mode-dropdown" class="dropdown-submenu">
            {% if temConjuge %}
            <div class="dropdown-item" onclick="changeMode('S')">Casal</div>
            {% endif %}
            <div class="dropdown-item" onclick="changeMode('N')">Individual</div>
          </div>
    
          <div class="dropdown-item">
            Idioma
            <div class="language-selector">
              <span>Português</span>
              <img src="https://flagcdn.com/w40/br.png" alt="BR" width="16" />
            </div>
          </div>
    
          <div class="dropdown-item" onclick="signOut()">Sign out</div>
        </div>
      </div>
    </div>

  </div>


  <div class="settings-wrapper">
    <div class="settings-header">
      <h1>Configurações</h1>
      <div class="menu-icon">☰</div>
    </div>

    <div class="settings-options">
      <div class="option">
        <div class="icon">🔊</div>
        <span>Som</span>
        <label class="switch">
          <input type="checkbox" checked>
          <span class="slider"></span>
        </label>
      </div>

      <div class="option">
        <div class="icon">🔔</div>
        <span>Notificações</span>
        <label class="switch">
          <input type="checkbox">
          <span class="slider"></span>
        </label>
      </div>

      <!-- <div class="option">
        <div class="icon">🖼️</div>
        <span>Galeria</span>
        <label class="switch">
          <input type="checkbox">
          <span class="slider"></span>
        </label>
      </div>

      <div class="option">
        <div class="icon">🌐</div>
        <span>Navegador</span>
        <label class="switch">
          <input type="checkbox" checked>
          <span class="slider"></span>
        </label>
      </div>
    </div> -->

    <div class="settings-footer">
      <!-- <div class="footer-icon">👤</div>
      <div class="footer-icon">☁️</div> -->
      <div class="footer-icon">⚙️</div>
      <span>Excluir Conta</span>
    </div>
  </div>


</div>

 <!-- Modal confirmação  -->
 <div id="modal-confirmar-exclusao" class="modal" style="display: none;">
  <div class="modal-content">
    <span class="close" id="fechar-modal-excluir">&times;</span>
    <h3>Tem certeza que deseja excluir sua conta?</h3>
    <form method="POST" action="{{ url_for('admin.deletar_usuario') }}"> 
      <input type="hidden" id="id-usuario-excluir" name="id">
      <button type="submit" id="confirmar-exclusao" class="btn-ok" style="margin-top: 12px;">OK</button>
  </form>
  
  </div>
</div>


<div class="footer-bar">
  <a href="{{ url_for('gasto.index') }}">
    <button class="footer-btn">
      <span class="material-icons">dashboard</span>
      <span class="footer-text">Visão Geral</span>
    </button>
  </a>
  <a href="{{ url_for('despesa.despesas') }}">
    <button class="footer-btn">
      <span class="material-icons">bar_chart</span>
      <span class="footer-text">Despesas</span>
    </button>
  </a>
  <a href="{{ url_for('gasto.extrato') }}">
    <button class="footer-btn">
      <span class="material-icons">account_balance_wallet</span>
      <span class="footer-text">Transações</span>
    </button>
  </a>
  <!-- <a href="{{ url_for('despesa.metas') }}">
    <button class="footer-btn">
      <span class="material-icons">payment</span>
      <span class="footer-text">Limites</span>
    </button>
  </a> -->
    <a href="{{ url_for('gasto.configuracoes') }}">
    <button class="footer-btn active">
      <span class="material-icons">settings</span>
      <span class="footer-text">Configurações</span>
    </button>
  </a>
</div>

<script src="static/js/config.js" defer></script>
</body>
</html>

templates/extrato.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Extrato</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/extrato.css') }}">
    <script src="static/js/extrato.js" defer></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/litepicker/dist/css/litepicker.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.5.0/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/comum.css') }}">
    <script src="static/js/comum.js" defer></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/litepicker/dist/litepicker.js"></script>
</head>
<body>

    <div class="header-bar center">
        <div class="logo-text">
          <img src="{{ url_for('static', filename='images/A&A.png') }}" alt="Logo" class="logo">
          <span class="company-name">A&A - Finance Dashboard</span>
        </div>
    
        <div class="user-info">
          <div class="dropdown">
            <div class="dropdown-toggle" onclick="toggleDropdown()">
              <span class="material-icons user-icon">{% if isCasal == 'N' %}person {% else %} people {% endif %}</span>
            </div>
        
            <div id="main-dropdown" class="dropdown-menu">
              <div class="profile-header">
                <span  id="user-icon" class="material-icons profile-icon">{% if isCasal == 'N' %}person {% else %} people {% endif %}</span>
                <div  id="current-username"  class="profile-name">{{ usuario.split('@')[0] | upper }}</div>
              </div>
        
              <div class="dropdown-item" onclick="toggleModeDropdown()">
                Modo
                <span class="material-icons">expand_more</span>
              </div>
        
              <!-- submenu do modo -->
              <div id="mode-dropdown" class="dropdown-submenu">
                {% if temConjuge %}
                <div class="dropdown-item" onclick="changeMode('S')">Casal</div>
                {% endif %}
                <div class="dropdown-item" onclick="changeMode('N')">Individual</div>
              </div>
        
              <div class="dropdown-item">
                Idioma
                <div class="language-selector">
                  <span>Português</span>
                  <img src="https://flagcdn.com/w40/br.png" alt="BR" width="16" />
                </div>
              </div>
        
              <div class="dropdown-item" onclick="signOut()">Sign out</div>
            </div>
          </div>
        </div>
    
      </div>
      

    <div class="container-detalhes" >

        <h2 style="text-align: center;">Extrato</h2>

        <div class="filtro-container">

<!-- Filtro -->
<form method="GET" action="{{ url_for('gasto.extrato') }}" class="filtro-form" id="filtro-form">
    <!-- Botão de período -->
    <div class="periodo-wrapper">
        <label for="data">Período:</label>
        <input type="text" id="periodo-picker" readonly placeholder="Selecione o período" />
        <input type="hidden" id="data_inicio" name="data_inicio" value="{{ data_inicio }}">
<input type="hidden" id="data_fim" name="data_fim" value="{{ data_fim }}">

<!-- <input type="hidden" id="categoria" name="categoria" value="{{ categoria }}"> -->
    </div>
    <!-- Dropdown de categoria -->
    <label for="categoria">Categoria:</label>
    <select name="categoria" id="categoria">
        <option value="Todas">Todas</option>
        <option value="Alimentação">Alimentação</option>
        <option value="Saúde">Saúde</option>
        <option value="Mobilidade">Mobilidade</option>
        <option value="Entretenimento">Entretenimento</option>
        <option value="Moradia">Moradia</option>
        <option value="Outros">Outros</option>
        <option value="Dívidas">Dívidas</option>
        <option value="Educação">Educação</option>

        {% for cat in categorias %}
            <option value="{{ cat }}" {% if request.args.get('categoria') == cat %}selected{% endif %}>{{ cat }}</option>
        {% endfor %}
    </select>

    <button type="submit" class="botao-filtrar">Filtrar</button>
</form>

<!-- dele/dela (só exibir se for visualziacao de casal)--> 
{% if isCasal == 'S' %} <!--(só exibir se for visualziacao de casal)--> 
<div class="casal">
  <div class="casal-item">
    <span class="casal-icon dele"></span>
    <span class="casal-texto">Ele</span>
  </div>
  <div class="casal-item">
    <span class="casal-icon dela"></span>
    <span class="casal-texto">Ela</span>
  </div>
</div>
{% endif %}

</div>
<br>

        <table>
            <thead>
                <tr>
                    <!-- <th>Data</th> -->
                    <th>Categoria</th>
                    <th>Descrição</th>
                    <th>Valor (R$)</th>
                    <th colspan="2"> </th>

                    <!-- <th></th> -->
                </tr>
            </thead>
            <tbody>
             

                {% for data, lista in gastos_agrupados.items() %}
                <!-- Linha com a data -->
                <tr style="background-color: #f5f5f5d2;">
                    <td colspan="5" style="text-align: justify; padding: 8px 0;"><strong>📅 {{ data }}</strong></td>
                </tr>
            
                {% for gasto in lista %}
                    <tr class="gasto"
                    data-id="{{ gasto[4] }}"
                     
                     style="background-color: {% if  gasto[5]  == 'S' %}rgba(247, 236, 247, 0.65){% else %}rgba(128, 255, 238, 0.25) {% endif %}; line-height: 1.6;"
                     >
                        <td>{{ gasto[0] }}</td>
                        <td>{{ gasto[1] }}</td>
                        <td>R$ {{ gasto[2] | round(2) }}</td>
                        <td>
                            <i class="fas fa-edit edit-icon"
                            data-data="{{ gasto[3] }}"
                            data-categoria="{{ gasto[0] }}"
                            data-descricao="{{ gasto[1] }}"
                            data-valor="{{ gasto[2] }}"
                            data-id="{{ gasto[4] }}"
                            title="Editar"></i>
                        </td>
                        <td>
                            <i class="fa-solid fa-trash"
                            data-id="{{ gasto[4] }}"
                            ></i>
                        </td>
                    </tr>
                {% endfor %}
            {% endfor %}
            

              </tbody>
              <tfoot>
                <tr>
                    <td colspan="2" style="text-align: left; font-weight: bold;">Total do período:</td>
                    <td></td>
                    <td colspan="2" style="font-weight: bold;">
                        R$ {{ '%.2f' | format(soma_gastos) }}
                    </td>
                </tr>
                
            </tfoot>
            
                      

        </table>

        <div style="text-align: right; margin-top: 10px;">

          <button class="btn-left">Adicionar Gasto</button> 

            <a href="{{ url_for('gasto.exportar_excel', data_inicio=request.args.get('data_inicio'), data_fim=request.args.get('data_fim'), categoria=request.args.get('categoria')) }}" class="button-detalhes" style="background: linear-gradient(135deg, #28a745, #218838);">Exportar Excel</a>

            <a id="enviapdf" href="{{ url_for('gasto.exportar_pdf', data_inicio=request.args.get('data_inicio'), data_fim=request.args.get('data_fim'), categoria=request.args.get('categoria')) }}" class="button-detalhes" style="background: linear-gradient(135deg, #e04b4bc9, #e62121);">Exportar PDF</a>
        </div>


        <!-- Paginação  REMOVIDO PAGINACAO-->
     

        <br><br><br><br>
    </div>

    <div class="footer-bar">
      <a href="{{ url_for('gasto.index') }}">
        <button class="footer-btn">
          <span class="material-icons">dashboard</span>
          <span class="footer-text">Visão Geral</span>
        </button>
      </a>    
        <a href="{{ url_for('despesa.despesas') }}">
          <button class="footer-btn">
            <span class="material-icons">bar_chart</span>
            <span class="footer-text">Despesas</span>
          </button>
        </a>
        <a href="{{ url_for('gasto.extrato') }}">
          <button class="footer-btn active">
            <span class="material-icons">account_balance_wallet</span>
            <span class="footer-text">Transações</span>
          </button>
        </a>
        <!-- <a href="{{ url_for('despesa.metas') }}">
          <button class="footer-btn">
            <span class="material-icons">payment</span>
            <span class="footer-text">Limites</span>
          </button>
        </a> -->
        <a href="{{ url_for('gasto.configuracoes') }}">
            <button class="footer-btn">
            <span class="material-icons">settings</span>
            <span class="footer-text">Configurações</span>
            </button>
        </a>
      </div>

<!-- Modal de Edição -->
<div id="modal-editar" class="modal" style="display: none;">
    <div class="modal-content">
      <span class="close" id="fechar-modal">&times;</span>
      <h3>Editar Gasto</h3>
      <form id="form-editar" method="POST" action="{{ url_for('gasto.editar_gasto') }}">
        <label for="editar-data">Data:</label>
        <input type="date" name="data" id="editar-data">
  
        <label for="editar-categoria">Categoria:</label>
        <!-- <input type="text" name="categoria" id="editar-categoria" required> -->
        <select name="categoria" id="editar-categoria">

            <option value="Alimentação">Alimentação</option>
            <option value="Saúde">Saúde</option>
            <option value="Mobilidade">Mobilidade</option>
            <option value="Entretenimento">Entretenimento</option>
            <option value="Moradia">Moradia</option>
            <option value="Outros">Outros</option>
            <option value="Dívidas">Dívidas</option>
            <option value="Educação">Educação</option>
        </select>
        <label for="editar-descricao">Descrição:</label>
        <input type="text" name="gasto" id="editar-descricao" required>
  
        <label for="editar-valor">Valor (R$):</label>
        <input type="number" step="0.01" name="valor" id="editar-valor" required>
  
        <input type="hidden" id="editar-id" name="id">

        <button type="submit" class="botao-salvar">Salvar</button>
      </form>
    </div>
  </div>
  
 <!-- Modal confirmação  -->
 <div id="modal-confirmar-exclusao" class="modal" style="display: none;">
    <div class="modal-content">
      <span class="close" id="fechar-modal-excluir">&times;</span>
      <h3>Tem certeza que deseja excluir este gasto?</h3>
      <form method="POST" action="{{ url_for('gasto.deletar_gasto') }}"> 
        <input type="hidden" id="id-gasto-excluir" name="id">
        <button type="submit" id="confirmar-exclusao" class="btn-ok" style="margin-top: 12px;">OK</button>
    </form>
    
    </div>
  </div>
  

<!-- Modal de Cadastro -->
<div id="modal-cadastrar" class="modal" style="display: none;">
    <div class="modal-content">
      <span class="close" id="fechar-modal-cadastro">&times;</span>
      <h3>Cadastrar Gasto</h3>
      <form id="form-cadastrar" method="POST" action="{{ url_for('gasto.cadastrar_gasto') }}">
        <label for="cadastrar-data">Data:</label>
        <input type="date" name="data" id="cadastrar-data">
  
        <label for="cadastrar-categoria">Categoria:</label>
        <!-- <input type="text" name="categoria" id="cadastrar-categoria" required> -->
        <select name="categoria" id="cadastrar-categoria">

            <option value="Alimentação">Alimentação</option>
            <option value="Saúde">Saúde</option>
            <option value="Mobilidade">Mobilidade</option>
            <option value="Entretenimento">Entretenimento</option>
            <option value="Moradia">Moradia</option>
            <option value="Outros">Outros</option>
            <option value="Dívidas">Dívidas</option>
            <option value="Educação">Educação</option>
        </select>
        <label for="cadastrar-descricao">Descrição:</label>
        <input type="text" name="gasto" id="cadastrar-descricao" required>
  
        <label for="cadastrar-valor">Valor (R$):</label>
        <input type="number" step="0.01" name="valor" id="cadastrar-valor" required>
  
        <input type="hidden" id="cadastrar-id" name="id">

        <button type="submit" class="botao-salvar">Salvar</button>
      </form>
    </div>
  </div>


 <!-- Modal ok  -->
 <div id="modal-cadastro-ok" class="modal" style="display: none;">
    <div class="modal-content">
      <span class="close" id="fechar-modal-ok">&times;</span>
      <h4>Gasto Cadastrado com sucesso!</h4>
      <form method="POST"> 
        <input type="hidden" id="id-gasto" name="id">
        <button type="submit" id="confirmar-ok" class="botao-salvar" style="margin-top: 12px;">OK</button>
    </form>
    
    </div>
  </div>

<!-- Modal mensalista  -->
<div id="modal-mensalista" class="modal" style="display: none;">
    <div class="modal-content" style="background-color: #e96960;">
      <span class="mensalista" id="fechar-modal-mensalista">&times;</span>
      <h4 style="text-align: center; color: #f5f5f5;">Assinatura de mensalista vencida!</h4>
      <h4 style="text-align: center; color: #f5f5f5;">Contate o administrador.</h4>  
      <button type="submit" id="confirmar-ok" class="btn-ok" style="margin-top: 12px;">OK</button>  
    </div>
  </div>

</body>
</html>